rm -rf /var/cache/apt/*
rm -rf /var/lib/apt/*
rm -rf /var/lib/dpkg/*
rm -rf /var/lib/cache/*
rm -rf /var/lib/log/*
rm -rf /var/tmp/*
rm -rf /tmp/*
rm -rf /usr/share/i18n/
rm -rf /usr/share/doc/
rm -rf /usr/share/locale/
rm -rf /usr/share/man/
rm -rf /usr/sbin/locale-gen
rm -rf /usr/sbin/update-locale
rm -rf /usr/sbin/validlocale